jenkins modifyy

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -29,5 +29,26 @@ pipeline {
                 }
             }
         }
+
+        stage('Run Container') {
+            steps {
+                sh """
+                    docker stop ecommerce || true
+                    docker rm ecommerce || true
+                    docker pull $REPO:$TAG
+                    docker run -d -p 9091:80 --name ecommerce $REPO:$TAG
+                """
+            }
+        }
+    }
+
+    post {
+        success {
+            echo "🚀 Site running at: http://<SERVER_IP>:9091"
+        }
+        failure {
+            echo "❌ Build/Deploy failed. Check logs!"
+        }
     }
 }
+
