Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -2,33 +2,45 @@ pipeline {
     agent any
 
     environment {
-        IMAGE_NAME = "ecommerce-frontend"
-        TAG = "${env.BUILD_NUMBER}"
+        DOCKER_IMAGE = 'ecommerce-java'
+        DOCKER_TAG = 'latest'
+        REGISTRY = 'docker.io'
+        REPO = 'chakriamajaladocker'  // replace with DockerHub username
     }
 
     stages {
         stage('Checkout') {
             steps {
-                checkout scm
+                git 'https://github.com/ChakriAmajala/e-commerce-web-site.git'
             }
         }
 
         stage('Build Docker Image') {
             steps {
-                sh "docker build -t $IMAGE_NAME:$TAG ."
+                sh 'docker build -t $REGISTRY/$REPO/$DOCKER_IMAGE:$DOCKER_TAG .'
             }
         }
 
-        stage('Run Container') {
+        stage('Push to Docker Hub') {
             steps {
-                echo "Stopping old container if exists..."
-                sh "docker stop ecommerce || true"
-                sh "docker rm ecommerce || true"
-
-                echo "Running container..."
-                sh "docker run -d --name ecommerce -p 9095:80 $IMAGE_NAME:$TAG"
-                sh "docker ps -a"
+                withCredentials([usernamePassword(credentialsId: 'dockerhub4', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
+                    sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
+                    sh 'docker push $REGISTRY/$REPO/$DOCKER_IMAGE:$DOCKER_TAG'
+                }
             }
         }
+
+        stage('Deploy') {
+            steps {
+                sh 'docker stop ecommerce-container || true'
+                sh 'docker rm ecommerce-container || true'
+                sh 'docker run -d --name ecommerce-container -p 8002:8080 $REGISTRY/$REPO/$DOCKER_IMAGE:$DOCKER_TAG'
+            }
+        }
+    }
+
+    post {
+        success { echo 'Java E-commerce app built, pushed, and deployed successfully!' }
+        failure { echo 'Build failed.' }
     }
 }
